In [1]:
import numpy as np
import pandas as pd

In [26]:
df =pd.read_csv(r'countries.csv')

In [27]:
df

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),Phones (per 1000),Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service
0,Afghanistan,ASIA (EX. NEAR EAST),31056997,647500,"48,0","0,00","23,06","163,07",700.0,"36,0","3,2","12,13","0,22","87,65",1,"46,6","20,34","0,38","0,24","0,38"
1,Albania,EASTERN EUROPE,3581655,28748,"124,6","1,26","-4,93","21,52",4500.0,"86,5","71,2","21,09","4,42","74,49",3,"15,11","5,22","0,232","0,188","0,579"
2,Algeria,NORTHERN AFRICA,32930091,2381740,"13,8","0,04","-0,39",31,6000.0,"70,0","78,1","3,22","0,25","96,53",1,"17,14","4,61","0,101","0,6","0,298"
3,American Samoa,OCEANIA,57794,199,"290,4","58,29","-20,71","9,27",8000.0,"97,0","259,5",10,15,75,2,"22,46","3,27",NaN,NaN,NaN
4,Andorra,WESTERN EUROPE,71201,468,"152,1","0,00","6,6","4,05",19000.0,"100,0","497,2","2,22",0,"97,78",3,"8,71","6,25",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222,West Bank,NEAR EAST,2460492,5860,"419,9","0,00","2,98","19,62",800.0,NaN,"145,2","16,9","18,97","64,13",3,"31,67","3,92","0,09","0,28","0,63"
223,Western Sahara,NORTHERN AFRICA,273008,266000,"1,0","0,42",NaN,NaN,NaN,NaN,NaN,"0,02",0,"99,98",1,NaN,NaN,NaN,NaN,"0,4"
224,Yemen,NEAR EAST,21456188,527970,"40,6","0,36",0,"61,5",800.0,"50,2","37,2","2,78","0,24","96,98",1,"42,89","8,3","0,135","0,472","0,393"
225,Zambia,SUB-SAHARAN AFRICA,11502010,752614,"15,3","0,00",0,"88,29",800.0,"80,6","8,2","7,08","0,03","92,9",2,41,"19,93","0,22","0,29","0,489"
226,Zimbabwe,SUB-SAHARAN AFRICA,12236805,390580,"31,3","0,00",0,"67,69",1900.0,"90,7","26,8","8,32","0,34","91,34",2,"28,01","21,84","0,179","0,243","0,579"

questions of dataset

In [74]:
df.columns

Index(['Country', 'Region', 'Population', 'Area (sq. mi.)',
       'Pop. Density (per sq. mi.)', 'Coastline (coast/area ratio)',
       'Net migration', 'Infant mortality (per 1000 births)',
       'GDP ($ per capita)', 'Literacy (%)', 'Phones (per 1000)', 'Arable (%)',
       'Crops (%)', 'Other (%)', 'Climate', 'Birthrate', 'Deathrate',
       'Agriculture', 'Industry', 'Service'],
      dtype='str')

In [ ]:
# country with the highest number of population
df[df["Population"]==df["Population"].max()]

In [ ]:
# Coastline of the courtry 
df[df["Population"]==df["Population"].max()]["Coastline (coast/area ratio)"]

In [ ]:
# country with the least number of population
df[df["Population"]==df["Population"].min()]

In [ ]:
#Coastline of the courtry 
df[df["Population"]==df["Population"].min()]["Coastline (coast/area ratio)"]

In [ ]:
# top 5 country with  highest litercy rate
df.sort_values(by='Literacy (%)',ascending= False,inplace= True)
df.head()

In [71]:
#total numbers for country in a region
df[df["Region"]== "NEAR EAST"]["Country"]

Series([], Name: Country, dtype: str)

In [55]:
#total numbers for region
df['Region'].value_counts().count()

np.int64(11)

In [ ]:
#number for counties that did't have any info about literacy%
df[df['Literacy (%)'].isna()]

In [ ]:
#how many country have northern africa in there name
count = 0
def counting(txt):
    global count
    if "NORTHERN AFRICA" in txt:
        count+=1
    return txt

In [102]:
df['Region'] = df['Region'].apply(counting)
print(count)

6

In [121]:
# no_coast_df dataframe
# which country have lowest migration
no_coast_df =df[df['Net migration'] <"1,00"]
no_coast_df[no_coast_df['Net migration']==no_coast_df['Net migration'].max()]

,Country,Region,Population,Area (sq. mi.),Pop. Density (per sq. mi.),Coastline (coast/area ratio),Net migration,Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),Phones (per 1000),Arable (%),Crops (%),Other (%),Climate,Birthrate,Deathrate,Agriculture,Industry,Service
190,Spain,WESTERN EUROPE,40397842,504782,"80,0","0,98","0,99","4,42",22000.0,"97,9","453,5","26,07","9,87","64,06",3,"10,06","9,72","0,04","0,295","0,665"