Loading dataset and libraries

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [3]:
ipl = pd.read_csv("Book_ipl22_ver_33.csv")
ipl.head()

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,second_ings_score,second_ings_wkts,match_winner,won_by,margin,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure
0,1,"March 26,2022","Wankhede Stadium, Mumbai",Chennai,Kolkata,Group,Kolkata,Field,131,5,133,4,Kolkata,Wickets,6,Umesh Yadav,MS Dhoni,50,Dwayne Bravo,3--20
1,2,"March 27,2022","Brabourne Stadium, Mumbai",Delhi,Mumbai,Group,Delhi,Field,177,5,179,6,Delhi,Wickets,4,Kuldeep Yadav,Ishan Kishan,81,Kuldeep Yadav,3--18
2,3,"March 27,2022","Dr DY Patil Sports Academy, Mumbai",Banglore,Punjab,Group,Punjab,Field,205,2,208,5,Punjab,Wickets,5,Odean Smith,Faf du Plessis,88,Mohammed Siraj,2--59
3,4,"March 28,2022","Wankhede Stadium, Mumbai",Gujarat,Lucknow,Group,Gujarat,Field,158,6,161,5,Gujarat,Wickets,5,Mohammed Shami,Deepak Hooda,55,Mohammed Shami,3--25
4,5,"March 29,2022","Maharashtra Cricket Association Stadium,Pune",Hyderabad,Rajasthan,Group,Hyderabad,Field,210,6,149,7,Rajasthan,Runs,61,Sanju Samson,Aiden Markram,57,Yuzvendra Chahal,3--22

Basic info

In [ ]:
ipl.info()
ipl.describe()

In [ ]:
ipl.shape
ipl.isna().sum()

Basic questions from dataset

In [ ]:
#Which team won the most match
match_won =ipl["match_winner"].value_counts()
sns.barplot(y = match_won.index , x = match_won.values,palette= "rainbow")

In [ ]:
#toss decision Trends
toss =ipl["toss_decision"]
sns.countplot(toss,palette= "rainbow")

In [42]:
# toss wins vs match wins
count = ipl[ipl["toss_winner"] == ipl["match_winner"]]["match_id"].count()
percentange = (count * 100)/74
percentange.round(2)

np.float64(48.65)

In [ ]:
#how do teams wins.(Runs vs wickets)
ipl['won_by'].value_counts()

Key players performance

In [50]:
#most player of the match awards
counts =ipl['player_of_the_match'].value_counts().head(10)

In [ ]:
#top scorers
high = ipl.groupby('top_scorer')['highscore'].sum().sort_values(ascending= False).head(5)
high.plot(kind = 'barh')

In [ ]:
#top 10 best bolling figure
ipl["highest_wickets"] = ipl["best_bowling_figure"].apply(lambda x : x.split("--")[0])
ipl['highest_wickets'] = ipl['highest_wickets'].astype(int)
top_bowler = ipl.groupby("best_bowling")["highest_wickets"].sum()
gg =top_bowler.sort_values(ascending= False).head(5)
gg.plot(kind = 'barh')

Some custom questions

In [9]:
#who won the highest margin by runs
ipl[ipl["won_by"] == "Runs"].sort_values(by ="margin" , ascending = False)[["match_winner", "margin"]].head(1)

   match_winner  margin
54      Chennai      91

In [5]:
#which player have the highest individual score
ipl[ipl['highscore'] == ipl['highscore'].max()].head(5)[["top_scorer" , 'highscore']]

         top_scorer  highscore
65  Quinton de Kock        140

In [58]:
#which player hade the best bowling figure
ipl[ipl['highest_wickets']==ipl['highest_wickets'].max()].tail(1)[['best_bowling', "best_bowling_figure"]]

      best_bowling best_bowling_figure
55  Jasprit Bumrah               5--10